# White a script that read a int number and show your multiplication table;

value = int(input('Type a value: '))
print('-' * 12)
print('{} * 1 = {}'.format(value, value * 1))
print('{} * 2 = {}'.format(value, value * 2))
print('{} * 3 = {}'.format(value, value * 3))
print('{} * 4 = {}'.format(value, value * 4))
print('{} * 5 = {}'.format(value, value * 5))
print('{} * 6 = {}'.format(value, value * 6))
print('{} * 7 = {}'.format(value, value * 7))
print('{} * 8 = {}'.format(value, value * 8))
print('{} * 9 = {}'.format(value, value * 9))
print('{} * 10 = {}'.format(value, value * 10))
print('-' * 12)
